# **K-Mode Clustering을 진행하기 위해 결제 카드별 결제 금액 TOP 3 카테고리 뽑기**  
# 1. 라이브러리 불러오기

In [1]:
import pandas as pd

In [2]:
cust_info = pd.read_csv('/content/drive/MyDrive/CARD-LANGCHAIN/data/회원정보.csv')
payment = pd.read_csv('/content/drive/MyDrive/CARD-LANGCHAIN/data/결제데이터.csv')

In [3]:
cust_info.head(2)

  발급회원번호  남녀구분코드   연령  Life_Stage
0  SYN_0       2  40대  5.자녀성장기(2)
1  SYN_1       1  30대  4.자녀성장기(1)

In [ ]:
payment.head(2)

,발급회원번호,이용금액_쇼핑,이용금액_요식,이용금액_교통,이용금액_의료,이용금액_납부,이용금액_교육,이용금액_여유생활,이용금액_사교활동,이용금액_일상생활,...,여유_전체이용금액,납부_통신비이용금액,납부_관리비이용금액,납부_렌탈료이용금액,납부_가스전기료이용금액,납부_보험료이용금액,납부_유선방송이용금액,납부_건강연금이용금액,납부_기타이용금액,납부_전체이용금액
0,SYN_0,140824,0,30598,46086,192847,0,0,67281,34349,...,0,0,0,0,0,188356,0,0,4491,192847
1,SYN_1,215804,0,165965,89730,208328,0,0,162964,0,...,0,208328,0,0,0,0,0,0,0,208328

In [ ]:
payment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 45 columns):
 #   Column        Dtype
---  ------        -----
 0   발급회원번호        object
 1   이용금액_쇼핑       int64
 2   이용금액_요식       int64
 3   이용금액_교통       int64
 4   이용금액_의료       int64
 5   이용금액_납부       int64
 6   이용금액_교육       int64
 7   이용금액_여유생활     int64
 8   이용금액_사교활동     int64
 9   이용금액_일상생활     int64
 10  이용금액_해외       int64
 11  쇼핑_도소매_이용금액   int64
 12  쇼핑_백화점_이용금액   int64
 13  쇼핑_마트_이용금액    int64
 14  쇼핑_슈퍼마켓_이용금액  int64
 15  쇼핑_편의점_이용금액   int64
 16  쇼핑_아울렛_이용금액   int64
 17  쇼핑_온라인_이용금액   int64
 18  쇼핑_기타_이용금액    int64
 19  쇼핑_전체_이용금액    int64
 20  교통_주유이용금액     int64
 21  교통_정비이용금액     int64
 22  교통_통행료이용금액    int64
 23  교통_버스지하철이용금액  int64
 24  교통_택시이용금액     int64
 25  교통_철도버스이용금액   int64
 26  교통_전체이용금액     int64
 27  여유_운동이용금액     int64
 28  여유_Pet이용금액    int64
 29  여유_공연이용금액     int64
 30  여유_공원이용금액     int64
 31  여유_숙박이용금액     int64
 32  여유_여행이용금액     int64
 33  여유_항공이용금액     int64
 34  여유_기타이용금액     int64
 35  여유_전체이용금액     int64
 36  납부_통신비이용금액    int64
 37  납부_관리비이용금액    int64
 38  납부_렌탈료이용금액    int64
 39  납부_가스전기료이용금액  int64
 40  납부_보험료이용금액    int64
 41  납부_유선방송이용금액   int64
 42  납부_건강연금이용금액   int64
 43  납부_기타이용금액     int64
 44  납부_전체이용금액     int64
dtypes: int64(44), object(1)
memory usage: 1.0+ GB

In [ ]:
df_all = pd.merge(cust_info, payment, how='right', on = '발급회원번호')

In [ ]:
df_all.to_csv('회원정보_결제데이터.csv',index=False)

In [ ]:
payment.loc[payment['발급회원번호'] == 'SYN_1000']

,발급회원번호,이용금액_쇼핑,이용금액_요식,이용금액_교통,이용금액_의료,이용금액_납부,이용금액_교육,이용금액_여유생활,이용금액_사교활동,이용금액_일상생활,...,여유_전체이용금액,납부_통신비이용금액,납부_관리비이용금액,납부_렌탈료이용금액,납부_가스전기료이용금액,납부_보험료이용금액,납부_유선방송이용금액,납부_건강연금이용금액,납부_기타이용금액,납부_전체이용금액
1000,SYN_1000,403492,35289,188080,0,0,0,271321,162298,36180,...,271321,0,0,0,0,0,0,0,0,0

In [ ]:
payment['교통_버스지하철이용금액'].head()

0    10578
1        0
2        0
3        0
4        0
Name: 교통_버스지하철이용금액, dtype: int64

In [ ]:
payment['교통_버스지하철이용금액'].describe()

count    3.000000e+06
mean     1.477382e+04
std      3.547259e+04
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.191490e+05
Name: 교통_버스지하철이용금액, dtype: float64

# 2. 데이터 전처리

In [ ]:
df_payment = payment[['발급회원번호', '이용금액_쇼핑','이용금액_요식','이용금액_교통','이용금액_의료','이용금액_납부','이용금액_교육',
'이용금액_여유생활','이용금액_사교활동','이용금액_일상생활','이용금액_해외']]

In [ ]:
df_payment['전체금액'] = df_payment.iloc[:,1:].sum(axis=1)

<ipython-input-6-f4325fbcecb5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_payment['전체금액'] = df_payment.iloc[:,1:].sum(axis=1)

In [ ]:
df_pay = df_payment[~(df_payment['전체금액'] == 0)].drop('전체금액',axis=1).reset_index(drop=True)

In [ ]:
df_pay.head()

,발급회원번호,이용금액_쇼핑,이용금액_요식,이용금액_교통,이용금액_의료,이용금액_납부,이용금액_교육,이용금액_여유생활,이용금액_사교활동,이용금액_일상생활,이용금액_해외
0,SYN_0,140824,0,30598,46086,192847,0,0,67281,34349,0
1,SYN_1,215804,0,165965,89730,208328,0,0,162964,0,0
2,SYN_2,73052,0,0,0,0,0,0,70739,0,0
3,SYN_3,0,0,49234,0,0,0,0,0,0,0
4,SYN_7,0,0,0,0,2320,0,0,0,0,0

In [ ]:
df_pay.iloc[:,1:].idxmax(axis=1)

0            이용금액_납부
1            이용금액_쇼핑
2            이용금액_쇼핑
3            이용금액_교통
4            이용금액_납부
             ...
2399339      이용금액_쇼핑
2399340    이용금액_사교활동
2399341      이용금액_쇼핑
2399342      이용금액_납부
2399343      이용금액_쇼핑
Length: 2399344, dtype: object

# 3. TOP3 카테고리 추출

In [ ]:
df_pay['category'] = df_pay.iloc[:,1:].apply(lambda s: s.abs().nlargest(3).index.tolist(), axis=1)

In [ ]:
df_pay['category']

0          [이용금액_납부, 이용금액_쇼핑, 이용금액_사교활동]
1            [이용금액_쇼핑, 이용금액_납부, 이용금액_교통]
2          [이용금액_쇼핑, 이용금액_사교활동, 이용금액_요식]
3            [이용금액_교통, 이용금액_쇼핑, 이용금액_요식]
4            [이용금액_납부, 이용금액_쇼핑, 이용금액_요식]
                       ...
2399339    [이용금액_쇼핑, 이용금액_해외, 이용금액_사교활동]
2399340    [이용금액_사교활동, 이용금액_쇼핑, 이용금액_납부]
2399341      [이용금액_쇼핑, 이용금액_납부, 이용금액_교통]
2399342    [이용금액_납부, 이용금액_쇼핑, 이용금액_사교활동]
2399343    [이용금액_쇼핑, 이용금액_교통, 이용금액_사교활동]
Name: category, Length: 2399344, dtype: object

In [ ]:
df_pay.to_csv('top_payment.csv',index=False)

In [ ]:
df_pay.explode('category')

,발급회원번호,이용금액_쇼핑,이용금액_요식,이용금액_교통,이용금액_의료,이용금액_납부,이용금액_교육,이용금액_여유생활,이용금액_사교활동,이용금액_일상생활,이용금액_해외,category
0,SYN_0,140824,0,30598,46086,192847,0,0,67281,34349,0,이용금액_납부
0,SYN_0,140824,0,30598,46086,192847,0,0,67281,34349,0,이용금액_쇼핑
0,SYN_0,140824,0,30598,46086,192847,0,0,67281,34349,0,이용금액_사교활동
1,SYN_1,215804,0,165965,89730,208328,0,0,162964,0,0,이용금액_쇼핑
1,SYN_1,215804,0,165965,89730,208328,0,0,162964,0,0,이용금액_납부
...,...,...,...,...,...,...,...,...,...,...,...,...
2399342,SYN_2999998,145557,0,46842,0,244652,0,21262,126770,0,116487,이용금액_쇼핑
2399342,SYN_2999998,145557,0,46842,0,244652,0,21262,126770,0,116487,이용금액_사교활동
2399343,SYN_2999999,219717,0,125150,0,0,0,0,105314,0,0,이용금액_쇼핑
2399343,SYN_2999999,219717,0,125150,0,0,0,0,105314,0,0,이용금액_교통
2399343,SYN_2999999,219717,0,125150,0,0,0,0,105314,0,0,이용금액_사교활동

In [ ]:
df_top = pd.DataFrame(df_pay['category'].to_list(),columns=['top1','top2','top3'])
df_top.to_csv('top_category.csv',index=False)

In [ ]:
df_top['top1'] = df_top['top1'].str.replace('이용금액_','')
df_top['top2'] = df_top['top2'].str.replace('이용금액_','')
df_top['top3'] = df_top['top3'].str.replace('이용금액_','')

In [ ]:
df_top = pd.concat([df_top, df_pay['발급회원번호']], axis=1)

In [ ]:
df_top.to_csv('top_category.csv',index=False)

# 4. 고객 개인정보와 TOP 결제 카테고리 합치기

In [ ]:
cust_info
df_all = pd.merge(cust_info, df_top, how='right', on = '발급회원번호')

In [ ]:
df_all.to_csv('customer_top3_payment.csv',index=False)